### ISSUE TITLE
README still mentions missing Redis example

### ISSUE THREAD

**Issue by Blaisorblade** [jepsen-io/knossos#11]
I read
> See knossos.core for the linearizability checker, and knossos.redis for an model that can generate histories verifiable with Knossos.

I was confused by not finding knossos.redis or variations, till I dug into history and found 08166a4bb85310ccd7ea1628ff886b38442360a6. What's an example model to get started now?

**Comment by aphyr** [comment]
Cleaned up stale refs from the readme, thanks.
