### ISSUE TITLE
Unhelpful error message when trying to render failed portion of a history

### ISSUE THREAD

**Issue by mpalmer** [jepsen-io/knossos#36]
Hi,

I'm using Knossos to verify linearizability on a history generated by a distributed system that is, for now, modelling a register.  The checker is reporting that the history is not linearizable, but when I ask for a rendering of the problem sections, I get the error

```
Execution error (AssertionError) at knossos.linear.report/time-coords$fn (report.clj:184).
Assert failed: Expected index but got nil for op #knossos.op.Op{:process nil, :type nil, :f nil, :value nil, :index nil}
```

Given that I'm writing out a history "by hand", I'm *assuming* that I've done something wrong, but the current error being reported isn't helping me determine what exactly I'm doing wrong.

[This is the history file I'm using](https://github.com/jepsen-io/knossos/files/4830031/edn.txt), and this is what I'm doing to try and render it (which has worked with other broken histories in the past, so I'm pretty sure it's *capable* of working):

```
knossos.cli=> (require '[knossos.model :as model] '[knossos.competition :as competition])
nil
knossos.cli=> (require '[knossos.linear.report :as report])
nil
knossos.cli=> (def h (read-history "edn.txt"))
#'knossos.cli/h
knossos.cli=> (def a (competition/analysis (model/register) h))
Jun 25, 2020 5:51:51 PM clojure.tools.logging$eval1047$fn__1050 invoke
INFO: More than 1024 reachable models; not memoizing models for this search
#'knossos.cli/a
knossos.cli=> Jun 25, 2020 5:51:51 PM clojure.tools.logging$eval1047$fn__1050 invoke
INFO: More than 1024 reachable models; not memoizing models for this search
knossos.cli=> (report/render-analysis! h a "linear.svg")

Execution error (AssertionError) at knossos.linear.report/time-coords$fn (report.clj:185).
Assert failed: Expected index but got nil for op #knossos.op.Op{:process nil, :type nil, :f nil, :value nil, :index nil}
```

Any assistance appreciated.

**Comment by aphyr** [comment]
Huh! Yeah, presumably the history is malformed in some way, and you're right, that error message isn't helpful.

**Comment by mpalmer** [comment]
Aha!  I can fairly easily make sure that the first operation in my stress tester is a write, if that'll make for a happy knossos.  Thanks for the pointer (and for the software).

**Comment by aphyr** [comment]
You don't even need to do that! Take a look at the docs for (register)... It should take an initial value as an argument. :)On Jun 25, 2020 18:13, Matt Palmer <notifications@github.com> wrote:
Aha!  I can fairly easily make sure that the first operation in my stress tester is a write, if that'll make for a happy knossos.  Thanks for the pointer (and for the software).

**Comment by mpalmer** [comment]
That was just my temporary "hack" to see if the history was otherwise linearizable.  The fix in my stress tester was to stop (erroneously) turning `nil` into `0` when writing out the history file.
